 config-version: 1
# The root folder for the database change scripts
# root-folder: null

# The modules folder for jinja macros and templates to be used across multiple scripts.
 modules-folder: null

# The name of the snowflake account (e.g. xy12345.east-us-2.azure)
 snowflake-account: 'ie12226.west-europe.azure'

# The name of the snowflake user
 snowflake-user: 'ETL_USER'

# The snowflake private key path for the user
 snowflake-private-key-path: {{env_var('DEV_Private_Key_Path')}}


# The name of the default role to use. Can be overrideen in the change scripts.
 snowflake-role: 'ETL_ROLE'

# The name of the default warehouse to use. Can be overridden in the change scripts.
 snowflake-warehouse: 'DATA_TEAM_WH'

# The name of the default database environment to use. Can be overridden in the change scripts.
 snowflake-database-env: DEV

# Used to override the default name of the change history table (the default is METADATA.SCHEMACHANGE.CHANGE_HISTORY)
 change-history-table: SCHEMA_CHANGE.CHANGE_HISTORY

# Define values for the variables to replaced in change scripts
 vars:
  "datalake_env": "dev" # "dev" for dev "tst" for test  datalake storage accounts;
  "accountscore_datalake_env" : "tstuks" #"tstuks" for accountscore storage account;
  "bureau_glass_datalake_env" : "tst"
  "decision_engine_db" : "DEV_DECISION_ENGINE"
  "decision_engine_preprocessor_db" : "DEV_DECISION_ENGINE_PREPROCESSOR"
  "accountscore_db" : "DEV_ACCOUNTSCORE"
  "quote_db" : "DEV_QUOTE"
  "Venus_Live_db": "DEV_VENUS_LIVE"
  "file_drop_db": "DEV_FILE_DROP"
  "sandbox_db": "DEV_SANDBOX"
  "admin_db": "DEV_ADMIN"
  "collections_db": "DEV_COLLECTIONS"
  "consumerauto_quote_db": "DEV_CONSUMERAUTO_QUOTE"
  "consumerauto_vehicleservice_db": "DEV_CONSUMERAUTO_VEHICLESERVICE"
  "dwh_legacy_db": "DEV_DWH_LEGACY"
  "security_role": "DEV"
  "Bureau_CallCredit_db": "DEV_BUREAU_CALLCREDIT"
  "Bureau_Glass_db": "DEV_BUREAU_GLASS"
  "consumerauto_vehicleregistration_db": "DEV_CONSUMERAUTO_VEHICLEREGISTRATION"
  "consumerauto_contractacceptance_db": "DEV_CONSUMERAUTO_CONTRACTACCEPTANCE"
  "consumerauto_compliancechecks_db": "DEV_CONSUMERAUTO_COMPLIANCECHECKS"
  "consumerauto_invoice_db": "DEV_CONSUMERAUTO_INVOICE"
  "Bureau_Equifax_db": "DEV_BUREAU_EQUIFAX"
  "loancollections_db": "DEV_LOANCOLLECTIONS"
  "pricing_db": "DEV_PRICING"


# Create the change history schema and table, if they do not exist (the default is False)
 create-change-history-table: true

# Enable autocommit feature for DML commands (the default is False)
 autocommit: false

# Display verbose debugging details during execution (the default is False)
 verbose: true

# Run schemachange in dry run mode (the default is False)
 dry-run: false    


