CREATE OR REPLACE TABLE STAGING.dbo_Addresses(
	ID NUMBER(38,0) NOT NULL,
	CheckStatus NUMBER(38,0) NULL,
	CheckStatusName varchar(100) NULL,
	UDPRN varchar(50) NULL,
	ElectoralRollStatus NUMBER(38,0) NULL,
	AddressType NUMBER(38,0) NOT NULL,
	AddressTypeName varchar(100) NULL,
	UserId NUMBER(38,0) NOT NULL,
	AbodeNumber varchar(255) NULL,
	BuildingNumber varchar(255) NULL,
	BuildingName varchar(255) NULL,
	Company varchar(255) NULL,
	Department varchar(255) NULL,
	Line1 varchar(255) NULL,
	Line2 varchar(255) NULL,
	Line3 varchar(255) NULL,
	Line4 varchar(255) NULL,
	Line5 varchar(255) NULL,
	PrimaryStreet varchar(255) NULL,
	SecondaryStreet varchar(255) NULL,
	DoubleDependentLocality varchar(255) NULL,
	DependentLocality varchar(255) NULL,
	Town varchar(255) NULL,
	PostCode varchar(10) NULL,
	County varchar(255) NULL,
	Country varchar(255) NULL,
	POBox varchar(255) NULL,
	Mailsort varchar(50) NULL,
	DPS varchar(50) NULL,
	Barcode varchar(50) NULL,
	AddressUsage varchar(50) NULL,
	YearIn NUMBER(38,0) NULL,
	YearOut NUMBER(38,0) NULL,
	MonthsAtAddress NUMBER(38,0) NULL,
	Updated varchar(50) NULL,
	AddressStatus NUMBER(38,0) NULL,
	PartyId NUMBER(38,0) NULL,
	PostCodeCompact varchar(10) NULL,
	CompanyID NUMBER(38,0) NULL,
	FK_Application NUMBER(38,0) NULL,
	ApplicationType NUMBER(38,0) NULL,
	ApplicationTypeName varchar(100) NULL,
	FirstDateOnElectoralRoll TIMESTAMP_NTZ(9) NULL,
	MonthsAtAddressUserEntered NUMBER(38,0) NULL,
	CreateDate TIMESTAMP_NTZ(9) NULL,
	UpdateDate TIMESTAMP_NTZ(9) NULL,
	/* MetaData Columns*/
	Source_System varchar(100) null,
	Snapshot_Date TIMESTAMP_NTZ(9) null,	
	hash_key varchar(200) NOT NULL,
    PRIMARY KEY(ID )
);