CREATE OR REPLACE TABLE STAGING.DBO_BORROWERLOANPAYMENTS (
	ID NUMBER(38,0) NOT NULL,
	PaymentNumber float NULL,
	SettlementDate TIMESTAMP_NTZ(9) NULL,
	PaymentDate TIMESTAMP_NTZ(9) NULL,
	Amount NUMBER(38,0) NULL,
	PaymentStatus NUMBER(38,0) NULL,
	OutstandingAmount NUMBER(38,0) NULL,
	SettlementCapital NUMBER(38,0) NULL,
	SettlementInterest NUMBER(38,0) NULL,
	CreditRateFee NUMBER(38,0) NULL,
	LoanFee NUMBER(38,0) NULL,
	PaymentType NUMBER(38,0) NULL,
	DDSubmissionDate TIMESTAMP_NTZ(9) NULL,
	SettlementStatus NUMBER(38,0) NULL,
	PaymentReference varchar(50) NULL,
	Active NUMBER(38,0) NULL,
	PeriodDate TIMESTAMP_NTZ(9) NULL,
	AssignmentFee NUMBER(38,0) NULL,
	OriginalPaymentID NUMBER(38,0) NULL,
	CreateDate TIMESTAMP_NTZ(9) NULL,
	GUID VARCHAR(64) NULL,
	UserID NUMBER(38,0) NULL,
	BorrowerLoanID NUMBER(38,0) NULL,
	SequenceType NUMBER(38,0) NULL,
	IsEstimate NUMBER(38,0) NULL,
	RedemptionType NUMBER(38,0) NULL,
	RateFee NUMBER(38,0) NULL,
	FailureType NUMBER(38,0) NULL,
	FailedFlag NUMBER(38,0) NULL,
	FailedReason NUMBER(38,0) NULL,
	BankAccountID NUMBER(38,0) NULL,
	PartnerFeeContribution NUMBER(38,0) NULL,
	FileID NUMBER(38,0) NOT NULL,
	PartnerFee NUMBER(38,0) NULL,
	Fee_Borrower NUMBER(38,0) NULL,
	Fee_SwapAdjustment NUMBER(38,0) NULL,
	Fee_FundingAdjustment NUMBER(38,0) NULL,
	Fee_Service NUMBER(38,0) NULL,
	Fee_Credit NUMBER(38,0) NULL,
	Fee_Partner NUMBER(38,0) NULL,
	Fee_ServiceAdjustment NUMBER(38,0) NULL,
	CreditFactorFee NUMBER(38,0) NULL,
	StandingOrderProcessingMethod NUMBER(38,0) NOT NULL,
	StandingOrderRolloverRejected NUMBER(38,0) NULL,
	StandingOrderCashDate TIMESTAMP_NTZ(9) NULL,
	FailureChannel NUMBER(38,0) NULL,
	SubmissionAmount NUMBER(38,0) NULL,
	PFCover NUMBER(38,0) NOT NULL,
	/* MetaData Columns*/
	Source_System varchar(100) null,
	Snapshot_Date TIMESTAMP_NTZ(9) null,	
	hash_key varchar(200) NOT NULL,
	PRIMARY KEY (ID)
 );
