CREATE OR REPLACE TABLE staging.dbo_Users(
	UserId int  NOT NULL,
	UserGUID VARCHAR(64) NOT NULL,
	Username varchar(1024) NULL,
	CreateDate datetime NOT NULL,
	UpdateDate datetime NOT NULL,
	AccountStatus int NULL,
	IdentityStatus int NULL,
	IdentityCheckCount int NULL,
	LoginAttempts int NULL,
	LastLoginDate datetime NULL,
	CurrentLoginDate datetime NULL,
	OriginalIPAddress varchar(50) NULL,
	CurrentIPAddress varchar(50) NULL,
	Title varchar(30) NULL,
	FirstName varchar(30) NULL,
	OtherNames varchar(30) NULL,
	LastName varchar(30) NULL,
	DateOfBirth datetime NULL,
	RSAccountNumber varchar(50) NULL,
	DDInstructionCompleted INT NULL,
	TrackingSource varchar(255) NULL,
	TrackingPromo varchar(255) NULL,
	TrackingCreative varchar(255) NULL,
	TrackingUrl nvarchar(2000) NULL,
	TrackingKeywords nvarchar(2000) NULL,
	RunCreditChecks int NULL,
	LatestIdentityScore int NULL,
	BorrowerLevel int NULL,
	LenderLevel int NULL,
	Affiliate varchar(255) NULL,
	AffiliateCode varchar(255) NULL,
	AffiliateId varchar(255) NULL,
	RegisteredDate datetime NULL,
	LenderCommissionRate int NULL,
	FraudStatus int NULL,
	AcceptedDate datetime NULL,
	SessionPersistence int NULL,
	PreferredContactType int NULL,
	AssignedTo int NULL,
	IsAffiliate int NULL,
	RequestSource int NULL,
	ContactSetting int NULL,
	BorrowerNoReminders INT NULL,
	TermsAccepted int NULL,
	AdditionalCreditAllowed int NULL,
	FailedContact INT NULL,
	RSCustomerStatus int NULL,
	RSCreditStatus int NULL,
	ManualPaymentRef varchar(50) NULL,
	CurrentIdentityStatus int NULL,
	PIN varchar(10) NULL,
	PINSecurity int NULL,
	CIFASref varchar(10) NULL,
	CIFASStatus int NULL,
	PaymentWithdrawalStatus int NULL,
	OFAStatus int NULL,
	WrongPINEntry int NULL,
	ThirdPartyReference varchar(255) NULL,
	WithdrawalPendingStatus int NULL,
	FraudMatchStatus int NULL,
	IFA_ID int NULL,
	FCA_Accepted int NULL,
	RA_Accepted int NULL,
	CIFASListedOn date NULL,
	IFA_NoRI_Reminder INT NULL,
	IFA_NoIF_Reminder INT NULL,
	IFA_NoRI_EndDate datetime NULL,
	IFA_NoIF_EndDate datetime NULL,
	ConfirmedFraudDate datetime NULL,
	ReasonDeclinedAsLender int NULL,
	AccountType int NULL,
	CaseStudyStatus int NOT NULL,
	EOPStatus int NULL,
	PEPStatus int NOT NULL,
	AdditionalCreditAllowedSetDate datetime NULL,
	IPGeoLocation varchar(50) NULL,
	MasterUserID int NULL,
	NIN varchar(9) NULL,
	FirstDateOfCreditAtAnyAddress datetime NULL,
	RowVersion binary(8) NOT NULL,
	AffiliateUserId int NULL,
	/* MetaData Columns*/
	Source_System varchar(100) null,
	Snapshot_Date datetime null,	
	hash_key varchar(200) NOT NULL,	
		/*ENUM VALUES*/
    Account_Status_Name varchar(100) NULL,
    Identity_Status_Name varchar(100) NULL,
    Borrower_Level_Name varchar(100) NULL,
    Lender_Level_Name varchar(100) NULL,
    Fraud_Status_Name varchar(100) NULL,
    Preferred_Contact_Type_Name varchar(100) NULL,
    Request_Source_Name varchar(100) NULL,
    Contact_Setting_Name varchar(100) NULL,
    Terms_Accepted_Name varchar(100) NULL,
    RS_Customer_Status_Name varchar(100) NULL,
    RS_Credit_Status_Name varchar(100) NULL,
    Current_Identity_Status_Name varchar(100) NULL,
    CIFAS_Status_Name varchar(100) NULL,
    Payment_Withdrawal_Status_Name varchar(100) NULL,
    OFA_Status_Name varchar(100) NULL,
    Withdrawl_Pending_Status_Name varchar(100) NULL,
    Fraud_Match_Status_Name varchar(100) NULL,
    FCA_Accepted_Name varchar(100) NULL,
    RA_Accepted_Name varchar(100) NULL,
    Reason_Declined_As_Lender_Name varchar(100) NULL,
    Account_Type_Name varchar(100) NULL,
    Casestudy_Status_Name varchar(100) NULL,
    EOP_Status_Name varchar(100) NULL,
    PEP_Status_NAME varchar(100) NULL,
  PRIMARY KEY (UserId)
);

